import { User } from '../models/User.js';
import { PlatformSetting } from '../models/PlatformSetting.js';
import { Course, Lesson, Quiz, Question, Report, ReportAnalysis, Simulation, XrayAnalysis } from '../models/domain.js';
import { validRoles } from '../constants.js';
import { failure, success } from '../utils/response.js';

const page = (req) => Math.max(1, Number(req.query.page) || 1); const limit = (req) => Math.min(100, Math.max(1, Number(req.query.per_page) || 20));
export async function users(req, res) { const filter = req.query.search ? { $or: ['email', 'full_name'].map((key) => ({ [key]: new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') })) } : {}; const [items, total] = await Promise.all([User.find(filter).sort({ created_at: -1 }).skip((page(req) - 1) * limit(req)).limit(limit(req)), User.countDocuments(filter)]); return success(res, 'Users retrieved.', { users: items.map((x) => x.toPublicJSON()), pagination: { page: page(req), per_page: limit(req), total } }); }
export async function user(req, res) { const item = await User.findOne({ id: Number(req.params.user_id) }); return item ? success(res, 'User retrieved.', { user: item.toPublicJSON() }) : failure(res, 'User not found.', 404); }
export async function role(req, res) { if (!validRoles.includes(req.body.role)) return failure(res, 'Invalid role.', 400); const item = await User.findOneAndUpdate({ id: Number(req.params.user_id) }, { role: req.body.role }, { new: true }); return item ? success(res, 'User role updated.', { user: item.toPublicJSON() }) : failure(res, 'User not found.', 404); }
export async function status(req, res) { const item = await User.findOneAndUpdate({ id: Number(req.params.user_id) }, { is_active: Boolean(req.body.is_active) }, { new: true }); return item ? success(res, 'User status updated.', { user: item.toPublicJSON() }) : failure(res, 'User not found.', 404); }
export async function getSettings(_req, res) { const items = await PlatformSetting.find().lean(); return success(res, 'Settings retrieved.', { settings: Object.fromEntries(items.map((x) => [x.key, x.value])) }); }
export async function updateSettings(req, res) { await Promise.all(Object.entries(req.body).map(([key, value]) => PlatformSetting.findOneAndUpdate({ key }, { key, value }, { upsert: true }))); return getSettings(req, res); }
export async function resetSettings(_req, res) { await PlatformSetting.deleteMany({}); return success(res, 'Settings reset successfully.'); }
export async function overview(_req, res) { const [users, courses, quizzes, simulations, reports, analyses, xrays] = await Promise.all([User.countDocuments(), Course.countDocuments(), Quiz.countDocuments(), Simulation.countDocuments(), Report.countDocuments(), ReportAnalysis.countDocuments(), XrayAnalysis.countDocuments()]); return success(res, 'Platform overview retrieved.', { users, courses, quizzes, simulations, reports, report_analyses: analyses, xray_analyses: xrays }); }
const resources = { courses: Course, lessons: Lesson, quizzes: Quiz, questions: Question, simulations: Simulation, 'report-analyses': ReportAnalysis, 'xray-analyses': XrayAnalysis };
export async function resource(req, res) { const Model = resources[req.params.resource]; if (!Model) return failure(res, 'Resource not found.', 404); const query = req.params.id ? { id: Number(req.params.id) } : {}; if (req.method === 'GET') { const value = req.params.id ? await Model.findOne(query) : await Model.find(query).sort({ created_at: -1 }).lean(); return value ? success(res, 'Resource retrieved.', { [req.params.resource.replaceAll('-', '_')]: value }) : failure(res, 'Resource not found.', 404); } if (req.method === 'POST') return success(res, 'Resource created.', { resource: await Model.create(req.body) }, 201); if (req.method === 'DELETE') { const value = await Model.findOneAndDelete(query); return value ? success(res, 'Resource deleted.') : failure(res, 'Resource not found.', 404); } const value = await Model.findOneAndUpdate(query, req.body, { new: true, runValidators: true }); return value ? success(res, 'Resource updated.', { resource: value }) : failure(res, 'Resource not found.', 404); }
