import crypto from 'node:crypto';
import { roles } from '../constants.js';
import * as db from '../models/domain.js';
import { failure, success } from '../utils/response.js';

const id = (req) => Number(Object.values(req.params)[0]);
const owned = (req, extra = {}) => ({ user_id: req.user.id, ...extra });
const notFound = (res, label) => failure(res, `${label} not found.`, 404);
const list = (Model, key, filter = () => ({})) => async (req, res) => success(res, `${key} retrieved.`, { [key]: await Model.find(filter(req)).sort({ created_at: -1 }).lean() });
const get = (Model, label, filter = (req) => ({ id: id(req) })) => async (req, res) => { const item = await Model.findOne(filter(req)); return item ? success(res, `${label} retrieved.`, { [label.toLowerCase().replaceAll(' ', '_')]: item }) : notFound(res, label); };
const create = (Model, label, decorate = (_req, body) => body) => async (req, res) => { const item = await Model.create(decorate(req, { ...req.body })); return success(res, `${label} created successfully.`, { [label.toLowerCase().replaceAll(' ', '_')]: item }, 201); };
const update = (Model, label, filter = (req) => ({ id: id(req) })) => async (req, res) => { const item = await Model.findOneAndUpdate(filter(req), { $set: req.body }, { new: true, runValidators: true }); return item ? success(res, `${label} updated successfully.`, { [label.toLowerCase().replaceAll(' ', '_')]: item }) : notFound(res, label); };
const remove = (Model, label, filter = (req) => ({ id: id(req) })) => async (req, res) => { const item = await Model.findOneAndDelete(filter(req)); return item ? success(res, `${label} deleted successfully.`) : notFound(res, label); };

export const courses = {
  list: list(db.Course, 'courses'), get: get(db.Course, 'Course'), create: create(db.Course, 'Course', (req, body) => ({ ...body, instructor_id: req.user.id })), update: update(db.Course, 'Course'), remove: remove(db.Course, 'Course'),
  categories: list(db.CourseCategory, 'categories'), lessons: list(db.Lesson, 'lessons', (req) => ({ course_id: Number(req.params.course_id) })), lesson: get(db.Lesson, 'Lesson'), createLesson: create(db.Lesson, 'Lesson'), updateLesson: update(db.Lesson, 'Lesson'), removeLesson: remove(db.Lesson, 'Lesson'),
  enroll: async (req, res) => { const progress = await db.CourseProgress.findOneAndUpdate(owned(req, { course_id: Number(req.params.course_id) }), { $setOnInsert: { progress_percentage: 0, enrolled_at: new Date() } }, { upsert: true, new: true }); return success(res, 'Course enrollment successful.', { progress }, 201); },
  bookmark: async (req, res) => { const query = owned(req, { lesson_id: Number(req.params.lesson_id) }); if (req.method === 'DELETE') { await db.LessonBookmark.deleteOne(query); return success(res, 'Bookmark removed successfully.'); } const bookmark = await db.LessonBookmark.findOneAndUpdate(query, query, { upsert: true, new: true }); return success(res, 'Lesson bookmarked successfully.', { bookmark }, 201); },
  bookmarks: list(db.LessonBookmark, 'bookmarks', (req) => owned(req)),
  complete: async (req, res) => { const query = owned(req, { lesson_id: Number(req.params.lesson_id) }); const completed_lesson = await db.CompletedLesson.findOneAndUpdate(query, { ...query, completed_at: new Date() }, { upsert: true, new: true }); return success(res, 'Lesson completed successfully.', { completed_lesson }); },
  completed: list(db.CompletedLesson, 'completed_lessons', (req) => owned(req)), progress: list(db.CourseProgress, 'course_progress', (req) => owned(req)), recommendations: list(db.Recommendation, 'recommendations', (req) => owned(req)),
};

export const quizzes = {
  list: list(db.Quiz, 'quizzes'), get: async (req, res) => { const quiz = await db.Quiz.findOne({ id: Number(req.params.quiz_id) }).lean(); if (!quiz) return notFound(res, 'Quiz'); const questions = await db.Question.find({ quiz_id: quiz.id }).select('-correct_answer').lean(); return success(res, 'Quiz retrieved.', { quiz: { ...quiz, questions } }); },
  create: create(db.Quiz, 'Quiz', (req, body) => ({ ...body, created_by: req.user.id })), update: update(db.Quiz, 'Quiz', (req) => ({ id: Number(req.params.quiz_id) })), remove: remove(db.Quiz, 'Quiz', (req) => ({ id: Number(req.params.quiz_id) })),
  createQuestion: create(db.Question, 'Question', (req, body) => ({ ...body, quiz_id: Number(req.params.quiz_id) })), updateQuestion: update(db.Question, 'Question', (req) => ({ id: Number(req.params.question_id) })), removeQuestion: remove(db.Question, 'Question', (req) => ({ id: Number(req.params.question_id) })),
  submit: async (req, res) => { const quizId = Number(req.params.quiz_id); const questions = await db.Question.find({ quiz_id: quizId }).lean(); if (!questions.length) return notFound(res, 'Quiz'); const answers = req.body.answers ?? []; let correct = 0; questions.forEach((question, index) => { const answer = Array.isArray(answers) ? answers[index] : answers[question.id]; if (JSON.stringify(answer) === JSON.stringify(question.correct_answer)) correct += 1; }); const score = Math.round((correct / questions.length) * 100); const result = await db.Result.create({ user_id: req.user.id, quiz_id: quizId, answers, score, correct_answers: correct, total_questions: questions.length }); return success(res, 'Quiz submitted successfully.', { result }, 201); },
  results: list(db.Result, 'results', (req) => owned(req)), leaderboard: async (_req, res) => { const leaderboard = await db.Result.aggregate([{ $group: { _id: '$user_id', average_score: { $avg: '$score' }, quizzes_completed: { $sum: 1 } } }, { $sort: { average_score: -1 } }, { $limit: 100 }]); return success(res, 'Leaderboard retrieved.', { leaderboard: leaderboard.map((x) => ({ user_id: x._id, ...x, _id: undefined })) }); },
};

export const simulations = { list: list(db.Simulation, 'simulations'), get: get(db.Simulation, 'Simulation', (req) => ({ id: Number(req.params.simulation_id) })), create: create(db.Simulation, 'Simulation', (req, body) => ({ ...body, created_by: req.user.id })), update: update(db.Simulation, 'Simulation', (req) => ({ id: Number(req.params.simulation_id) })), remove: remove(db.Simulation, 'Simulation', (req) => ({ id: Number(req.params.simulation_id) })), history: list(db.SimulationAttempt, 'attempts', (req) => owned(req)), submit: async (req, res) => { const attempt = await db.SimulationAttempt.create({ user_id: req.user.id, simulation_id: Number(req.params.simulation_id), actions: req.body.actions, score: req.body.score ?? 0, feedback: req.body.feedback }); return success(res, 'Simulation submitted successfully.', { attempt }, 201); } };
export const cases = { list: list(db.ClinicalCase, 'cases'), get: get(db.ClinicalCase, 'Clinical case', (req) => ({ id: Number(req.params.case_id) })), create: create(db.ClinicalCase, 'Clinical case', (req, body) => ({ ...body, created_by: req.user.id })), update: update(db.ClinicalCase, 'Clinical case', (req) => ({ id: Number(req.params.case_id) })), remove: remove(db.ClinicalCase, 'Clinical case', (req) => ({ id: Number(req.params.case_id) })), favorites: list(db.CaseFavorite, 'favorites', (req) => owned(req)), favorite: async (req, res) => { const query = owned(req, { case_id: Number(req.params.case_id) }); if (req.method === 'DELETE') { await db.CaseFavorite.deleteOne(query); return success(res, 'Case removed from favorites.'); } const favorite = await db.CaseFavorite.findOneAndUpdate(query, query, { upsert: true, new: true }); return success(res, 'Case added to favorites.', { favorite }, 201); } };

async function toggleLike(Model, target, req, res) { const query = owned(req, { [target]: Number(req.params[target]) }); const existing = await Model.findOneAndDelete(query); if (existing) return success(res, 'Like removed.', { liked: false }); await Model.create(query); return success(res, 'Like added.', { liked: true }); }
export const discussions = { list: list(db.Discussion, 'discussions'), get: async (req, res) => { const discussion = await db.Discussion.findOne({ id: Number(req.params.discussion_id) }).lean(); if (!discussion) return notFound(res, 'Discussion'); const comments = await db.Comment.find({ discussion_id: discussion.id }).lean(); return success(res, 'Discussion retrieved.', { discussion: { ...discussion, comments } }); }, create: create(db.Discussion, 'Discussion', (req, body) => ({ ...body, user_id: req.user.id })), update: update(db.Discussion, 'Discussion', (req) => ({ id: Number(req.params.discussion_id), user_id: req.user.id })), remove: remove(db.Discussion, 'Discussion', (req) => ({ id: Number(req.params.discussion_id), user_id: req.user.id })), comment: create(db.Comment, 'Comment', (req, body) => ({ ...body, user_id: req.user.id, discussion_id: Number(req.params.discussion_id) })), removeComment: remove(db.Comment, 'Comment', (req) => ({ id: Number(req.params.comment_id), user_id: req.user.id })), like: (req, res) => toggleLike(db.DiscussionLike, 'discussion_id', req, res), likeComment: (req, res) => toggleLike(db.CommentLike, 'comment_id', req, res) };

export const notifications = { list: list(db.Notification, 'notifications', (req) => owned(req)), read: async (req, res) => { const notification = await db.Notification.findOneAndUpdate(owned(req, { id: Number(req.params.notification_id) }), { is_read: true }, { new: true }); return notification ? success(res, 'Notification marked as read.', { notification }) : notFound(res, 'Notification'); }, readAll: async (req, res) => { await db.Notification.updateMany(owned(req), { is_read: true }); return success(res, 'All notifications marked as read.'); }, remove: remove(db.Notification, 'Notification', (req) => owned(req, { id: Number(req.params.notification_id) })), reminder: async (req, res) => { const notification = await db.Notification.create({ user_id: req.user.id, notification_type: req.path.includes('quiz') ? 'quiz_reminder' : 'learning_reminder', title: req.body.title ?? 'Reminder', message: req.body.message ?? 'You have a learning activity waiting.', reference_id: req.body.reference_id }); return success(res, 'Reminder created.', { notification }, 201); }, create: create(db.Notification, 'Notification') };
export const progress = { get: async (req, res) => { const progress = await db.Progress.findOneAndUpdate(owned(req), { $setOnInsert: owned(req) }, { upsert: true, new: true }); return success(res, 'Progress retrieved.', { progress }); }, dashboard: async (req, res) => { const [progress, results, attempts] = await Promise.all([db.Progress.findOne(owned(req)).lean(), db.Result.countDocuments(owned(req)), db.SimulationAttempt.countDocuments(owned(req))]); return success(res, 'Dashboard retrieved.', { progress, quizzes_completed: results, simulations_completed: attempts }); }, achievements: async (req, res) => { const item = await db.Progress.findOne(owned(req)).lean(); return success(res, 'Achievements retrieved.', { achievements: item?.achievements ?? [] }); } };
export const certificates = { list: list(db.Certificate, 'certificates', (req) => owned(req)), get: get(db.Certificate, 'Certificate', (req) => owned(req, { id: Number(req.params.certificate_id) })), generate: async (req, res) => { const certificate = await db.Certificate.create({ user_id: req.user.id, course_id: req.body.course_id, certificate_number: `HUB-${crypto.randomBytes(6).toString('hex').toUpperCase()}` }); return success(res, 'Certificate generated successfully.', { certificate }, 201); } };
export const authorRoles = [roles.ADMIN, roles.DOCTOR];
