import fs from 'node:fs/promises';
import path from 'node:path';
import { Report, ReportAnalysis, XrayAnalysis } from '../models/domain.js';
import { failure, success } from '../utils/response.js';

const owned = (req, extra = {}) => ({ user_id: req.user.id, ...extra });
const fileData = (file) => ({ original_filename: file.originalname, stored_filename: file.filename, file_path: file.path, file_type: path.extname(file.originalname).slice(1).toLowerCase(), file_size: file.size });
const deleteFile = async (file) => { if (file) await fs.unlink(file).catch(() => undefined); };
export async function uploadReports(req, res) { const files = req.files?.length ? req.files : req.file ? [req.file] : []; if (!files.length) return failure(res, 'No files provided.', 400); const reports = await Report.create(files.map((file) => ({ user_id: req.user.id, title: req.body.title ?? file.originalname, report_type: req.body.report_type, ...fileData(file) }))); return success(res, 'Reports uploaded successfully.', { reports }, 201); }
export async function saveReport(req, res) { const report = await Report.create({ ...req.body, user_id: req.user.id }); return success(res, 'Report saved successfully.', { report }, 201); }
export async function listReports(req, res) { const reports = await Report.find(owned(req)).sort({ created_at: -1 }).lean(); return success(res, 'Reports retrieved.', { reports }); }
export async function getReport(req, res) { const report = await Report.findOne(owned(req, { id: Number(req.params.report_id) })); return report ? success(res, 'Report retrieved.', { report }) : failure(res, 'Report not found.', 404); }
export async function removeReport(req, res) { const report = await Report.findOneAndDelete(owned(req, { id: Number(req.params.report_id) })); if (!report) return failure(res, 'Report not found.', 404); await deleteFile(report.file_path); return success(res, 'Report deleted successfully.'); }
export async function extractReport(req, res) { const report = await Report.findOne(owned(req, { id: Number(req.params.report_id) })); if (!report) return failure(res, 'Report not found.', 404); if (!report.extracted_text) return failure(res, 'Text extraction is unavailable for this file type.', 422); return success(res, 'Text extracted successfully.', { report_id: report.id, extracted_text: report.extracted_text }); }
export async function analyzeReport(req, res) { const reportId = Number(req.body.report_id); const report = reportId ? await Report.findOne(owned(req, { id: reportId })) : null; if (reportId && !report) return failure(res, 'Report not found.', 404); const analysis = await ReportAnalysis.create({ user_id: req.user.id, report_id: report?.id, analysis_data: req.body.analysis_data ?? {}, summary: req.body.summary ?? null, confidence: req.body.confidence ?? null }); return success(res, 'Report analyzed successfully.', { analysis }, 201); }
export async function listAnalyses(req, res) { return success(res, 'Analyses retrieved.', { analyses: await ReportAnalysis.find(owned(req)).sort({ created_at: -1 }).lean() }); }
export async function getAnalysis(req, res) { const analysis = await ReportAnalysis.findOne(owned(req, { id: Number(req.params.analysis_id) })); return analysis ? success(res, 'Analysis retrieved.', { analysis }) : failure(res, 'Analysis not found.', 404); }
export async function removeAnalysis(req, res) { const analysis = await ReportAnalysis.findOneAndDelete(owned(req, { id: Number(req.params.analysis_id) })); return analysis ? success(res, 'Analysis deleted successfully.') : failure(res, 'Analysis not found.', 404); }
export async function uploadXrays(req, res) { const files = req.files ?? []; if (!files.length) return failure(res, 'No X-ray files provided.', 400); const xrays = await XrayAnalysis.create(files.map((file) => ({ user_id: req.user.id, filename: file.originalname, ...fileData(file), patient_age: req.body.patient_age, gender: req.body.gender, body_part: req.body.body_part, symptoms: req.body.symptoms, reason_for_exam: req.body.reason_for_exam, disclaimer: 'Educational use only. This output is not a medical diagnosis.' }))); return success(res, 'X-rays uploaded successfully.', { xrays }, 201); }
export async function listXrays(req, res) { const xrays = await XrayAnalysis.find(owned(req)).sort({ created_at: -1 }).lean(); return success(res, 'X-ray history retrieved.', { xrays }); }
export async function getXray(req, res) { const xray = await XrayAnalysis.findOne(owned(req, { id: Number(req.params.xray_id) })); return xray ? success(res, 'X-ray retrieved.', { xray }) : failure(res, 'X-ray not found.', 404); }
export async function removeXray(req, res) { const xray = await XrayAnalysis.findOneAndDelete(owned(req, { id: Number(req.params.xray_id) })); if (!xray) return failure(res, 'X-ray not found.', 404); await deleteFile(xray.file_path); return success(res, 'X-ray deleted successfully.'); }
export async function sendXray(req, res) { const xray = await XrayAnalysis.findOne(owned(req, { id: Number(req.params.xray_id) })); if (!xray) return failure(res, 'X-ray not found.', 404); return res.sendFile(path.resolve(xray.file_path)); }
export async function xrayDashboard(req, res) { const [total, completed, failed] = await Promise.all([XrayAnalysis.countDocuments(owned(req)), XrayAnalysis.countDocuments(owned(req, { status: 'completed' })), XrayAnalysis.countDocuments(owned(req, { status: 'failed' }))]); return success(res, 'X-ray dashboard retrieved.', { total, completed, failed }); }
