import crypto from 'node:crypto';
import { promisify } from 'node:util';

const pbkdf2 = promisify(crypto.pbkdf2);
const scrypt = promisify(crypto.scrypt);

const safeEqual = (left, right) => {
  const a = Buffer.from(left);
  const b = Buffer.from(right);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
};

// Supports hashes generated by Werkzeug 2.x/3.x so existing passwords survive migration.
export async function verifyPassword(password, encoded) {
  const [method, salt, expected] = String(encoded ?? '').split('$');
  if (!method || !salt || !expected) return false;
  const [algorithm, ...parameters] = method.split(':');
  let derived;
  if (algorithm === 'pbkdf2') {
    const digest = parameters[0] || 'sha256';
    const iterations = Number(parameters[1] || 260000);
    derived = (await pbkdf2(password, salt, iterations, Buffer.from(expected, 'hex').length, digest)).toString('hex');
  } else if (algorithm === 'scrypt') {
    const [N = 32768, r = 8, p = 1] = parameters.map(Number);
    derived = (await scrypt(password, salt, Buffer.from(expected, 'hex').length, { N, r, p, maxmem: 64 * 1024 * 1024 })).toString('hex');
  } else return false;
  return safeEqual(derived, expected);
}

export async function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  const N = 32768; const r = 8; const p = 1;
  const derived = await scrypt(password, salt, 64, { N, r, p, maxmem: 64 * 1024 * 1024 });
  return `scrypt:${N}:${r}:${p}$${salt}$${derived.toString('hex')}`;
}
